### ISSUE TITLE
即使没有flash,也会显示只不过是空白的

### ISSUE THREAD

**Issue by cnxfire** [LaravelChen/myflash#1]
$('.myflash-message').animate({top:'20px',opacity:1}).fadeIn('fast').delay(3000).fadeOut();
问题就出在这句上面了,应该加个判断吧!

**Comment by LaravelChen** [comment]
@cnxfire 对对！那个notification的视图里面忘记写一个session的判断！谢谢，已经改了!

**Comment by cnxfire** [comment]
谢谢!反应神速
